command:
  - bash
  - start.sh
env:
  - name: OTEL_TRACES_SAMPLER
    value: "always_on"
  - name: DATABRICKS_SQL_WAREHOUSE_PATH
    valueFrom: sql-warehouse
  - name: PGDATABASE
    value: lakebase_estimator
  - name: LAKEBASE_ENDPOINT
    valueFrom: PG_HOST
